### ISSUE TITLE
Module for Azure Linux Virtual Machine Scale Set as `azure-linux-vmss`

### ISSUE THREAD

**Issue by jcframil** [prefapp/tfm#398]
# Description :writing_hand: 

We need to create a Terraform module that enables the provisioning and configuration of **Linux Virtual Machine Scale Sets**.

# Requirements :receipt: 

- The module should support the creation of Linux Virtual Machine Scale Sets with dynamic public prefixes.
- We can provide different scripts for VM configuration:
  - **template_cloudinit_config**: VM configuration script
  - **run_script**: Init script

# Resource Configurations :wrench: 

The module should allow for configuring the following resources:
1. [Linux Virtual Machine Scale Sets](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set)
2.  [Public Prefix](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip_prefix.html)

# Input Variables :1234: 

```yaml
    values:
      tags:
        datacenter: "azure-westeurope"
        tenant: "example"
        application: "app"
        service: "service"
        env: "env"
        version: "v1.0"

      public_prefix:
        length: 29

      vmss:
        name: "example"
        sku: "Standard_D2as_v5"
        instances: 2
        admin_username: "azureuser"
        admin_ssh_key_username: "azureuser"
        image_publisher: "Canonical"
        image_offer: "0001-com-ubuntu-server-jammy"
        image_sku: "22_04-lts"
        image_version: "latest"
        disk_storage_account_type: "StandardSSD_LRS"
        disk_caching: "ReadWrite"
        network_primary: true
        network_ip_primary: true
        identity_type: "UserAssigned"
        prefix_length: 29
        upgrade_mode: "Automatic"
        subnet: "example_subnet"
        rg_name: "example_rg"
        managed_identity: "example_mi"
        public_key: "xxx"
        template_cloudinit_config: |
          #cloud-config
          ---
        run_script: |
          #!/bin/sh
          # Block until cloud-init completes
          cloud-init status --wait
          sleep 30s
```

# Output Variables :1234: 
- [id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#id-1) - The ID of the Linux Virtual Machine Scale Set.

- [unique_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#unique_id-1) - The Unique ID for this Linux Virtual Machine Scale Set.

- [identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#identity-2) - A identity block as defined below.

  - [principal_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#principal_id-1) - The Principal ID associated with this Managed Service Identity.

  - [tenant_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#tenant_id-1) - The Tenant ID associated with this Managed Service Identity.

# Documentation :book: 
Provide comprehensive documentation including examples.

# Acceptance Criteria :+1: 
The module is tested and validated with different configurations.
Code is well-structured, following Terraform best practices.
Comprehensive documentation and usage examples are provided.

# Tasklist :heavy_check_mark: 
```[tasklist]
### Tasks

```
