### ISSUE TITLE
Create AWS SSO module

### ISSUE THREAD

**Issue by arvegadev** [prefapp/tfm#4]
### Motivation

We need to code a  Terraform SSO Module that provides an easy way to manage SSO access.

### Acceptance Criteria

Given the following YAML file, code a terraform module that processses and provisions the SSO users, groups and permission sets.

```yaml
groups:
    

users:


permission-sets:
  - name: "permission-set-foo"
    custom-policies:
      - name: "custom-policy-foo"
    managed-policies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
    inline-policy:
      - name: "inline-policy-foo"
        #  We need to use jsonencode() method to avoid different ordering when we reapply terraform
        policy: | 
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "ec2:Describe*"
                ],
                "Resource": "*"
              }
            ]
          }


attachaments:
  account-0: 
      permission-set-foo:
          groups:
              - groupA
              - groupB
              - groupC
          users:
              - userA
              - userB
              - userC
  account-1: 
      permission-set-foo-2:
          groups:
              - groupC
          users:

```

### Docs

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group_membership
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user

@frmadem @jotasixto @alambike
