### ISSUE TITLE
Module for azure-public-prefix resource

### ISSUE THREAD

**Issue by jcframil** [prefapp/tfm#402]
# Description :writing_hand: 

We need to create a Terraform module that enables the provisioning and configuration of **azurerm_public_ip_prefix**.

# Requirements :receipt: 

- The module should support the creation of Azure Public IP Prefix

# Resource Configurations :wrench: 

The module should allow for configuring the following resources:
1.  [Public Prefix](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip_prefix.html)

# Input Variables :1234: 

```yaml
    values:
      name: "prefix_name"
      resource_group_name: "rg_name"
      location: "westeurope"
      sku: "Standard"
      sku_tier: "Regional"
      ip_version: "IPv4"
      prefix_length: 29
      zone: 1
      tags:
        tenant: "example"
        application: "app"
        service: "service"
        env: "env"
```

# Output Variables :1234: 
- [id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip_prefix#id-1) - The Public IP Prefix ID

- [ip_prefix](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip_prefix#ip_prefix-1) - The IP address prefix value that was allocated

# Documentation :book: 
Provide comprehensive documentation including examples.

# Acceptance Criteria :+1: 
The module is tested and validated with different configurations.
Code is well-structured, following Terraform best practices.
Comprehensive documentation and usage examples are provided.

# Tasklist :heavy_check_mark: 
```[tasklist]
### Tasks

```
