### ISSUE TITLE
Module for Azure Network Security Groups `azure-nsg`

### ISSUE THREAD

**Issue by jcframil** [prefapp/tfm#422]
# Description :writing_hand: 

We need to create a Terraform module that enables the provisioning and configuration of ** Azure Network Security Groups and the network security rules attached to it**.

# Requirements :receipt: 

- The module should support the creation of Azure Network Security Groups (NSG)
- The module should manage the creation of Network Security Rules (NSR)
- We can assing multiple NSR to a single NSG
- Each module can only manage a single NSG

# Resource Configurations :wrench: 

The module should allow for configuring the following resources:
1. [azurerm_network_security_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group)
2.  [azurerm_network_security_rule](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule)

# Input Variables :1234: 

```yaml
    values:
      nsg:
        name: "example"
        resource_group_name: "example_rg"
        tags:
          datacenter: "azure-westeurope"
          tenant: "example"
          application: "app"
          service: "service"
          env: "env"
          version: "v1.0"

      rules:
        https-port:
          name: "https-port"
          priority: 125
          source_address_prefix: "*"
          destination_address_prefix: "*"
          protocol: "Tcp"
          source_port_range: "*"
          access: "Allow"
          direction: "Inbound"
          destination_port_ranges:
            - "443"
        http-port:
          name: "http-port"
          priority: 128
          source_address_prefix: "*"
          destination_address_prefix: "*"
          protocol: "Tcp"
          source_port_range: "*"
          access: "Allow"
          direction: "Inbound"
          destination_port_ranges:
            - "80"
```

# Output Variables :1234: 
- [id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group#id-1) - The ID of the Network Security Group.

# Documentation :book: 
Provide comprehensive documentation including examples.

# Acceptance Criteria :+1: 
The module is tested and validated with different configurations.
Code is well-structured, following Terraform best practices.
Comprehensive documentation and usage examples are provided.

# Tasklist :heavy_check_mark: 
```[tasklist]
### Tasks

```
