### ISSUE TITLE
Modules for subscription policies: `azure-policy-definitions` and `azure-policy-assignments`

### ISSUE THREAD

**Issue by jcframil** [prefapp/tfm#450]
# Description :writing_hand:

We need to create Terraform modules that enables the provisioning and configuration of **policies for subscriptions**, for exampe: enforcing the inheritance of tags from resource groups to their resources.

This policies  should allow assignments at the **resource, resource group, subscription and management group level**.

# Requirements :receipt:

- The modules should define and apply an **Azure Policy** , like the one that ensures resources inherit tags from their parent resource group.
- The module should allow assignments at the **resource, resource group, subscription and management group level**.
- The modules should be flexible to accommodate additional policies in the future.
- The assignment module should be able to use custom and builtin policies by `display_name` (human readable)

# Update on Azure Policies Modules
There are now two separate modules for managing Azure policies in Terraform:

- `azure-policy-definitions` Module
- `azure-policiy-assignments` Module

## azure-policy-definitions Module

This module is responsible for creating Azure Policy Definitions.

### Resources

| Name | Type |
|------|------|
| [azurerm_policy_definition.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_definition) | resource |

### Inputs

| Name     | Description                                                                 | Type                                                                                                                                                                                                                                                                                                  | Default | Required |
|----------|-----------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|:--------:|
| policies | List of objects containing all the variables for the policy definitions.    | `list(object({<br/>    name                = string<br/>    policy_type         = string<br/>    mode                = string<br/>    display_name        = string<br/>    description         = optional(string)<br/>    management_group_id = optional(string)<br/>    policy_rule         = optional(string)<br/>    metadata            = optional(string)<br/>    parameters          = optional(string)<br/>  }))` | `[]`    | no       |

### Outputs

| Name                    | Description                                   |
|-------------------------|-----------------------------------------------|
| policy_definition_ids   | List of all Azure Policy definition IDs       |
| policy_definition_names | List of all Azure Policy definition names     |

### Example Usage (YAML)

```yaml
values:
  policies:
    - name: "example-policy"
      policy_type: "Custom"
      mode: "All"
      display_name: "Example Policy"
      description: "A sample policy to audit location."
      policy_rule: |
        {
          "if": {
            "field": "location",
            "equals": "westeurope"
          },
          "then": {
            "effect": "audit"
          }
        }
    - name: "example-policy2"
      policy_type: "Custom"
      mode: "All"
      display_name: "Example Policy 2"
      description: "A sample policy to audit location."
      policy_rule: |
        {
          "if": {
            "field": "location",
            "equals": "westeurope"
          },
          "then": {
            "effect": "audit"
          }
        }
```

## azure-policy-assignments Module

This module is used to assign Azure Policies at different scopes (e.g., resource group, management group, subscription).

### Resources

| Name                                                                                                                              | Type     |
|-----------------------------------------------------------------------------------------------------------------------------------|----------|
| [azurerm_management_group_policy_assignment.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_assignment) | resource |
| [azurerm_resource_group_policy_assignment.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_policy_assignment)   | resource |
| [azurerm_resource_policy_assignment.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_policy_assignment)           | resource |
| [azurerm_subscription_policy_assignment.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment)   | resource |
| [azurerm_management_group.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/management_group)                     | data source |
| [azurerm_policy_definition.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/policy_definition)                   | data source |
| [azurerm_resource_group.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/resource_group)                         | data source |
| [azurerm_subscription.current](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/subscription)                         | data source |

### Inputs

| Name        | Description                                                                                                              | Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Default | Required |
|-------------|--------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|:--------:|
| assignments | List of objects containing all the variables for the policy assignments.                                                | `list(object({<br/>    name                  = string<br/>    policy_type           = optional(string, "builtin")<br/>    policy_name           = optional(string)<br/>    policy_definition_id  = optional(string)<br/>    resource_id           = optional(string)<br/>    resource_group_id     = optional(string)<br/>    management_group_id   = optional(string)<br/>    resource_group_name   = optional(string)<br/>    management_group_name = optional(string)<br/>    scope                 = string<br/>    description           = optional(string)<br/>    display_name          = optional(string)<br/>    enforce               = optional(bool, true)<br/>    identity = optional(object({<br/>      type         = string<br/>      identity_ids = optional(list(string))<br/>    }))<br/>    location = optional(string)<br/>    metadata = optional(string)<br/>    non_compliance_message = optional(list(object({<br/>      content                        = string<br/>      policy_definition_reference_id = optional(string)<br/>    })))<br/>    not_scopes = optional(list(string))<br/>    parameters = optional(string)<br/>    overrides = optional(list(object({<br/>      value = string<br/>      selectors = optional(list(object({<br/>        in     = optional(list(string))<br/>        not_in = optional(list(string))<br/>      })))<br/>    })))<br/>    resource_selectors = optional(list(object({<br/>      name = optional(string)<br/>      selectors = list(object({<br/>        kind   = string<br/>        in     = optional(list(string))<br/>        not_in = optional(list(string))<br/>      }))<br/>    })))<br/>  }))` | `[]`    | no       |

### Outputs

| Name                                          | Description                                                  |
|-----------------------------------------------|--------------------------------------------------------------|
| management_group_policy_assignment_ids        | List of all Azure management group policy assignment IDs     |
| resource_group_policy_assignment_ids          | List of all Azure resource group policy assignment IDs       |
| resource_policy_assignment_ids                | List of all Azure resource policy assignment IDs             |
| subscription_policy_assignment_ids            | List of all Azure subscription policy assignment IDs         |

### Example Usage (YAML)

```yaml
values:
  assignments:
    - name: "example-assignment-3"
      policy_type: "custom"
      policy_name: "Example Policy"
      resource_id: "/subscriptions/2de29132-986f-482d-a49f-31441fc7992b/resourceGroups/test/providers/Microsoft.KeyVault/vaults/-test"
      scope: "resource"

    - name: "example-assignment-2"
      policy_type: "builtin"
      policy_name: "Allowed virtual machine size SKUs"
      resource_group_id: "/subscriptions/2de29132-986f-482d-a49f-31441fc7992b/resourceGroups/test"
      scope: "resource group"

    - name: "example-assignment-2"
      policy_type: "builtin"
      policy_name: "Allowed virtual machine size SKUs"
      resource_group_name: "test"
      scope: "resource group"

    - name: "example-assignment-1"
      policy_type: "builtin"
      policy_name: "Allowed locations"
      scope: "subscription"

    - name: "example-assignment-4"
      policy_type: "custom"
      policy_name: "Example Policy"
      management_group_name: "example"
      scope: "management group"
```
