### ISSUE TITLE
`terraform_backend` Add role to terraform_backend

### ISSUE THREAD

**Issue by alambike** [prefapp/tfm#662]
We need a new role with minimum permissions to manage state bucket and Dynamodb lock table:

- For Firestartr we want to create a role named: `aws_account_role=firestartr-<client_name>`
- We could also need an extra optional role, with the same permissions:
   `backend_extra_roles=[firestartr-github-<client_name>]`

### s3 bucket
https://developer.hashicorp.com/terraform/language/backend/s3#s3-bucket-permissions

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:ListBucket",
      "Resource": "arn:aws:s3:::mybucket",
      "Condition": {
        "StringEquals": {
          "s3:prefix": "mybucket/path/to/my/key"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": ["s3:GetObject", "s3:PutObject"],
      "Resource": [
        "arn:aws:s3:::mybucket/path/to/my/key"
      ]
    },
    {
      "Effect": "Allow",
      "Action": ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
      "Resource": [
        "arn:aws:s3:::mybucket/path/to/my/key.tflock"
      ]
    }
  ]
}

```

### DynamoDB table
https://developer.hashicorp.com/terraform/language/backend/s3#dynamodb-table-permissions
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "dynamodb:DescribeTable",
        "dynamodb:GetItem",
        "dynamodb:PutItem",
        "dynamodb:DeleteItem"
      ],
      "Resource": "arn:aws:dynamodb:*:*:table/mytable"
    }
  ]
}
```

### Cloud formation template to generate an admin Role for Firestartr

- role_name: **`FirestartrAdminRole`**

The generation of this template:
```terraform
var.generate_cloudformation_role_for_client_account = true
var.upload_cloudformation_role = true
```

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
    AdministratorRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: 'FirestartrAdminRole'
        Description: 'Administrator role for the AWS account, to the Firestartr service'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: "arn:aws:iam::111111111111:role/Role_A" <- role generated previously
              Action: 'sts:AssumeRole'
        ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
Outputs:
  AdministratorRole:
    Description: 'Firestartr Administrator role'
    Value: !Ref AdministratorRole
  AdministratorRoleArn:
    Description: 'Firestartr Administrator role ARN'
    Value: !GetAtt AdministratorRole.Arn
```

This generated role must be uploaded to the github repository, or to an s3 bucket:
- To upload to a github repository: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_file
- To publish it to an s3 bucket: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object
