### ISSUE TITLE
Add AzureAD group module

### ISSUE THREAD

**Issue by alambike** [prefapp/tfm#82]
Module inputs:

```yaml
name:  <group name>
members:   # list of AzureAD users, groups or service principals to assign to the group
  - type: user
    name: user1@domain (optional, name or object_id)
    object_id: xxx (optional, name or object_id)
  - type: group
    name: group_name (optional)
    object_id: xxx (optional)
  - type: service_principal
    object_id: xxx (mandatory)

owners: # list of AzureAD users or service principal owners of the group (should not be part of the members list)
  - type: user
    name: user1@domain
    object_id: xxx (optional, name or object_id)
  - type: service_principal
    object_id: xxxxx

subscription: <subscription id> (optional)
subscription_roles:  # Built-in roles to assign to the group (optionally the bonding can be static or PIM enabled)
  - resources_scopes: []
    role_name: role1
    pim:
        enabled: true | false # (default: false)
        type: active | eligible
        expiration_hours: # duration of the PIM (default 8h)
        justification_needed: true | false  (only needed in eligible type)
  - resource_scopes: []
    role_name: role2
    pim:
      enabled: true | false
      expiration_hours: duration of the PIM (default 8h)
      justification_needed: true | false

directory_roles:
    - role_name: role2
      pim:
        enabled: true | false (default: false)
        type: active | eligible
        expiration_hours: duration of the PIM (default 8h)
        justification_needed: true | false (only needed in eligible type)
```
